#!/bin/bash
# Generate .env from terraform outputs
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

cd infrastructure/terraform
BUCKET=$(terraform output -raw s3_bucket 2>/dev/null || true)
ATHENA_BUCKET=$(terraform output -raw athena_results_bucket 2>/dev/null || true)
GLUE_DB=$(terraform output -raw glue_database 2>/dev/null || true)

cd "$PROJECT_ROOT"

if [ -z "$ATHENA_BUCKET" ]; then
  echo "Run 'make deploy' first"
  exit 1
fi

cat > .env << EOF
# Generated by scripts/setup_env.sh
AWS_REGION=us-east-1

# Athena (dashboard)
GLUE_DATABASE=${GLUE_DB}
ATHENA_WORKGROUP=data-pipeline-demo
ATHENA_RESULTS_BUCKET=${ATHENA_BUCKET}
GLUE_TABLE=processed

# Redshift (optional)
USE_REDSHIFT=false
S3_BUCKET=${BUCKET}
EOF

echo "Created .env with ATHENA_RESULTS_BUCKET=${ATHENA_BUCKET}"
