#!/bin/bash
# Generate .env from terraform outputs
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

cd infrastructure/terraform
BUCKET=$(terraform output -raw s3_bucket 2>/dev/null || true)
ATHENA_BUCKET=$(terraform output -raw athena_results_bucket 2>/dev/null || true)
GLUE_DB=$(terraform output -raw glue_database 2>/dev/null || true)
STATE_MACHINE_ARN=$(terraform output -raw state_machine_arn 2>/dev/null || true)
AWS_REGION_OUT=$(terraform output -raw aws_region 2>/dev/null || true)

cd "$PROJECT_ROOT"

if [ -z "$ATHENA_BUCKET" ]; then
  echo "Run 'make deploy' first"
  exit 1
fi

# Match Terraform provider region (set -var="aws_region=..." when deploying)
AWS_REGION_VAL="${AWS_REGION_OUT:-us-east-1}"

cat > .env << EOF
# Generated by scripts/setup_env.sh
AWS_REGION=${AWS_REGION_VAL}

# Athena (dashboard)
GLUE_DATABASE=${GLUE_DB}
ATHENA_WORKGROUP=data-pipeline-demo
ATHENA_RESULTS_BUCKET=${ATHENA_BUCKET}
GLUE_TABLE=processed
STATE_MACHINE_ARN=${STATE_MACHINE_ARN}

# Redshift (optional)
USE_REDSHIFT=false
S3_BUCKET=${BUCKET}
EOF

echo "Created .env with ATHENA_RESULTS_BUCKET=${ATHENA_BUCKET}"

# Generate .bruin.yml for Bruin CLI (Athena connection)
cat > .bruin.yml << BRUIN
# Bruin - Athena connection (generated by setup_env.sh)
default_environment: dev

environments:
  dev:
    connections:
      athena:
        - name: athena-default
          region: ${AWS_REGION_VAL}
          database: ${GLUE_DB}
          profile: default
          query_results_path: s3://${ATHENA_BUCKET}/results/
BRUIN
echo "Created .bruin.yml with Athena connection (database=${GLUE_DB})"
echo ""
echo "To load env vars, run from project root:"
echo "  cd $PROJECT_ROOT && source .env"
echo "Or from anywhere:"
echo "  source $PROJECT_ROOT/.env"
